version: 0.0
os: linux
files:
  - source: /
    destination: /home/santa-builder/public_html/
hooks:
    BeforeInstall:  
    - location: /permissions.sh
      timeout: 600
    AfterInstall:
    - location: /ownership.sh