image: node:16.13.1
pipelines:
  branches:
    master:
    - step:
        caches:
          - node
        script:
          - apt-get update
          - apt-get install -y zip
          - npm cache clean --force
          - npm uninstall node-sass
          - npm i sass --save-dev
          - npm run sass-compile --style compressed
          - npm install
          - npm run build:wc:customizer:self
          - npm run build:wc:customizer:wordpress
          - npm run build:wc:orderdetail
          - npm run build
          # - npm run build:staging
          - zip -r application.zip .
          - pipe: atlassian/aws-code-deploy:0.5.3
            variables:
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              APPLICATION_NAME: $APPLICATION_NAME
              S3_BUCKET: $S3_BUCKET
              COMMAND: 'upload'
              ZIP_FILE: 'application.zip'
              VERSION_LABEL: 'custimoo-kitbuilder-2.0'
